In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [70]:
#Definimos el nombre de los controles
control_570_name_A = "Abs_570_G"
control_690_name_A = "Abs_690_G"

control_570_name_D = "Abs_570_H"
control_690_name_D = "Abs_690_H"
#Cargamos el archivo con los resultados del ensayo
df = pd.read_csv("ensayo_mtt.csv")
del df['Unnamed: 0']
sub_sample = df[(df.select_dtypes(include=['number']) != 0).any(1)].copy()
sub_sample.reset_index(inplace = True)
del sub_sample["index"]

#Cargamos los controlores
control_570_A = sub_sample.loc[:, control_570_name_A].copy()
control_690_A = sub_sample.loc[:, control_690_name_A].copy()

control_570_D = sub_sample.loc[:, control_570_name_D].copy()
control_690_D = sub_sample.loc[:, control_690_name_D].copy()


substraction_control_A = []
substraction_control_D = []
#ciclo para hacer la resta entre los controles (se necesita para hacer una regla de tres)
for i in range(0, len(control_570_A)):
    substraction_control_A.append(control_570_A.loc[i] - control_690_A.loc[i])
    substraction_control_D.append(control_570_D.loc[i] - control_690_D.loc[i])
substraction_control_A = np.array(substraction_control_A)
substraction_control_D = np.array(substraction_control_D)

mean_control_A = substraction_control_A.mean()
mean_control_D = substraction_control_D.mean()

control_percent_A = []
control_percent_D = []
#Porcentaje de lamedia con los dos controles
for i in range(0, len(control_570_A)):
    control_percent_A.append( (substraction_control_A[i] *100)/mean_control_A)
    control_percent_D.append( (substraction_control_D[i] *100)/mean_control_A)
#removemos los controles de la submuestra, ya sacamos los numeros que necesitamos de ellos
del sub_sample[control_570_name_A]
del sub_sample[control_690_name_A]
del sub_sample[control_570_name_D]
del sub_sample[control_690_name_D]


num_columns = len(sub_sample.columns) - 4 #quitamos  las cuatro columnas del control
pozos = len(sub_sample.index) #hasta donde corren los renglones
abs_subs = []
abs_prom = np.zeros([pozos, num_columns])
#hacemos la substraccion de las absorbancias entre 570nm y 690nm
for j in range(0, pozos):
    for k in range(0, num_columns - 2):
        abs_subs.append(sub_sample.iloc[j, 2*k] -  sub_sample.iloc[j, (2*k) + 1])


        
#calculamos una regla de tres para sacar la diferencia porcentual entre las restas y el promedio del control de las 
#celulas muertas

viabilidad = []

for abs_ in abs_subs:
    viabilidad.append( (abs_ * 100) / mean_control_A)

    
viabilidad = np.reshape(viabilidad, (pozos, num_columns - 2))
lon = viabilidad.shape[1]
viab_mean = np.zeros(lon)
for i in range(0, lon):
    viab_mean[i] = viabilidad[:, i].mean()
    

    
out_df = pd.DataFrame(viabilidad, columns = )

[99.0351481736733, 101.30944176430049, 99.65541006202619]

In [14]:
(abs_subs[9] * 100) / mean_control_A

52.515506547208815

In [69]:
substraction_control_D[0]

array([0.305, 0.303, 0.296])

In [23]:
print(viabilidad[9])
print(abs_subs[9])

52.515506547208815
0.254


In [71]:
control_percent_D

[63.059958649207424, 62.64645072363886, 61.19917298414885]

In [62]:
for i in range(0, lon):
    print(a[:, i])

[55.61681599 53.96278429 59.33838732]
[59.13163336 57.06409373 59.75189524]
[51.48173673 54.16953825 60.5789111 ]
[49.41419711 52.51550655 58.71812543]
[56.85733977 53.54927636 59.95864921]
[56.23707788 58.92487939 59.13163336]


In [73]:
viab_mean

array([56.30599586, 58.64920744, 55.41006203, 53.54927636, 56.78842178,
       58.09786354])

In [59]:
a.shape[1]

6

In [63]:
a[:,0].mean()

56.30599586492074